package oop_motorph;

import javax.swing.JOptionPane;
import java.awt.*;
import java.util.List;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.border.*;


public class frm_EmpSalary extends javax.swing.JFrame {

   
    public frm_EmpSalary() {
        initComponents();
        
        // Set window properties - larger size to show all content
        setResizable(true);
        setTitle("Payroll Information");
        setSize(1400, 950); // Increased size to accommodate all content
        setMinimumSize(new java.awt.Dimension(1150, 800));
        setLocationRelativeTo(null); // Center the window after setting size

        // Apply modern styling after components are initialized
        applyModernStyling();
        addHoverEffects();

        EmpDetails employee = EmpUserSession.getInstance().getCurrentUser();
        String role = EmpUserSession.getInstance().getRole();
        
        if (employee != null && role != null) {
            // Load salary data from CSV
            List<EmpSalaryDetails> salaryData = CSVHandler.getSalaryData();
            EmpSalaryDetails salaryDetails = null;

            // Find the salary details for the logged-in employee
            for (EmpSalaryDetails details : salaryData) {
                if (details.getEmpID().equals(employee.getEmpID())) {
                    salaryDetails = details;
                    break;
                }
            }

            if (salaryDetails != null) {
                // Set the salary data in the form
                setSalaryData(salaryDetails);
            } else {
                JOptionPane.showMessageDialog(this, "Salary data not found for the user!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            setRoleBasedAccess(role);
        } else {
            JOptionPane.showMessageDialog(this, "No employee data or role found!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Method to set salary data in the form
    private void setSalaryData(EmpSalaryDetails salaryDetails) {
        txt_sssNo.setText(salaryDetails.getSssNo());
        txt_philhealthNo.setText(salaryDetails.getPhilhealthNo());
        txt_tinNo.setText(salaryDetails.getTinNo());
        txt_pagibigNo.setText(salaryDetails.getPagibigNo());
        txt_basicSalary.setText(String.valueOf(salaryDetails.getBasicSalary()));
        txt_riceAllow.setText(String.valueOf(salaryDetails.getRiceSubsidy()));
        txt_phoneAllow.setText(String.valueOf(salaryDetails.getPhoneAllowance()));
        txt_clothingAllow.setText(String.valueOf(salaryDetails.getClothingAllowance()));
        txt_grossSemi.setText(String.valueOf(salaryDetails.getGrossSemi()));
        txt_hourlyRate.setText(String.valueOf(salaryDetails.getHourlyRate()));
    }

    // Set role-based access controls
    public void setRoleBasedAccess(String role) {
        // Disable all by default
        btn_LeaveMgt.setEnabled(false);
        btn_Profile.setEnabled(false);
        btn_Logout.setEnabled(false);
        btn_EmpRecords.setEnabled(false);
        btn_PayrollSummary.setEnabled(false);

        switch (role.toUpperCase()) {
            case "EMPLOYEE" -> {
                btn_LeaveMgt.setEnabled(true);
                btn_Profile.setEnabled(true);
                btn_Logout.setEnabled(true);
                btn_PayrollSummary.setEnabled(true);
            }
            case "HR" -> {
                btn_LeaveMgt.setEnabled(true);
                btn_Profile.setEnabled(true);
                btn_Logout.setEnabled(true);
                btn_EmpRecords.setEnabled(true);
                btn_PayrollSummary.setEnabled(true);
            }
            default -> {
                JOptionPane.showMessageDialog(this, "Access denied for role: " + role, "Permission Denied", JOptionPane.ERROR_MESSAGE);
                dispose(); // Close this frame if role is unauthorized
            }
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        txt_sssNo = new JTextField();
        txt_philhealthNo = new JTextField();
        txt_pagibigNo = new JTextField();
        txt_tinNo = new JTextField();
        txt_basicSalary = new JTextField();
        txt_riceAllow = new JTextField();
        txt_phoneAllow = new JTextField();
        txt_clothingAllow = new JTextField();
        txt_grossSemi = new JTextField();
        txt_hourlyRate = new JTextField();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        jLabel11 = new JLabel();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        jLabel14 = new JLabel();
        jLabel15 = new JLabel();
        jPanel3 = new JPanel();
        btn_Profile = new JButton();
        btn_LeaveMgt = new JButton();
        btn_SalaryAndStatutory = new JButton();
        btn_PayrollSummary = new JButton();
        jPanel4 = new JPanel();
        btn_MyRecords = new JButton();
        btn_EmpRecords = new JButton();
        btn_Logout = new JButton();
        jLabel1 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jPanel5 = new JPanel();
        jPanel6 = new JPanel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        var contentPane = getContentPane();

        //======== jPanel1 ========
        {
            jPanel1.setBorder(new CompoundBorder());

            //======== jPanel2 ========
            {
                jPanel2.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED, null, Color.lightGray, null, null));

                //---- txt_sssNo ----
                txt_sssNo.setEditable(false);

                //---- txt_philhealthNo ----
                txt_philhealthNo.setEditable(false);

                //---- txt_pagibigNo ----
                txt_pagibigNo.setEditable(false);

                //---- txt_tinNo ----
                txt_tinNo.setEditable(false);

                //---- txt_basicSalary ----
                txt_basicSalary.setEditable(false);

                //---- txt_riceAllow ----
                txt_riceAllow.setEditable(false);

                //---- txt_phoneAllow ----
                txt_phoneAllow.setEditable(false);

                //---- txt_clothingAllow ----
                txt_clothingAllow.setEditable(false);

                //---- txt_grossSemi ----
                txt_grossSemi.setEditable(false);

                //---- txt_hourlyRate ----
                txt_hourlyRate.setEditable(false);

                //---- jLabel6 ----
                jLabel6.setText("SSS Number:");

                //---- jLabel7 ----
                jLabel7.setText("Philhealth Number:");

                //---- jLabel8 ----
                jLabel8.setText("Pagibig Number:");

                //---- jLabel9 ----
                jLabel9.setText("TIN Number:");

                //---- jLabel10 ----
                jLabel10.setText("Basic Salary:");

                //---- jLabel11 ----
                jLabel11.setText("Rice Subsidy Allowance:");

                //---- jLabel12 ----
                jLabel12.setText("Phone Allowance:");

                //---- jLabel13 ----
                jLabel13.setText("Clothing Allowance:");

                //---- jLabel14 ----
                jLabel14.setText("Gross Semi-Monthly Rate:");

                //---- jLabel15 ----
                jLabel15.setText("Hourly Rate:");

                GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup()
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap(94, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
                            .addGap(52, 52, 52)
                            .addGroup(jPanel2Layout.createParallelGroup()
                                .addComponent(txt_sssNo, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_philhealthNo, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_pagibigNo, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_tinNo, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_basicSalary, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_riceAllow, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_phoneAllow, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_clothingAllow, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_grossSemi, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_hourlyRate, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE))
                            .addGap(74, 74, 74))
                );
                jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup()
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap(90, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(txt_sssNo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_philhealthNo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_pagibigNo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_tinNo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_basicSalary, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_riceAllow, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_phoneAllow, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel12))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_clothingAllow, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_grossSemi, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_hourlyRate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addGap(23, 23, 23))
                );
            }

            //======== jPanel3 ========
            {

                GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                    jPanel3Layout.createParallelGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel3Layout.setVerticalGroup(
                    jPanel3Layout.createParallelGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                );
            }

            //---- btn_Profile ----
            btn_Profile.setText("Profile");
            btn_Profile.addActionListener(e -> btn_ProfileActionPerformed(e));

            //---- btn_LeaveMgt ----
            btn_LeaveMgt.setText("Attendance & Leave");
            btn_LeaveMgt.addActionListener(e -> btn_LeaveMgtActionPerformed(e));

            //---- btn_SalaryAndStatutory ----
            btn_SalaryAndStatutory.setText("Salary & Statutory");
            btn_SalaryAndStatutory.addActionListener(e -> btn_SalaryAndStatutoryActionPerformed(e));

            //---- btn_PayrollSummary ----
            btn_PayrollSummary.setText("Payroll Summary");
            btn_PayrollSummary.addActionListener(e -> btn_PayrollSummaryActionPerformed(e));        //======== jPanel4 ========
        {

            GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                    jPanel4Layout.createParallelGroup()
                        .addGap(0, 1032, Short.MAX_VALUE)
                );
                jPanel4Layout.setVerticalGroup(
                    jPanel4Layout.createParallelGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                );
            }

            //---- btn_MyRecords ----
            btn_MyRecords.setText("My Records");
            btn_MyRecords.addActionListener(e -> btn_MyRecordsActionPerformed(e));

            //---- btn_EmpRecords ----
            btn_EmpRecords.setText("Employee Records");
            btn_EmpRecords.addActionListener(e -> btn_EmpRecordsActionPerformed(e));

            //---- btn_Logout ----
            btn_Logout.setText("Logout");
            btn_Logout.addActionListener(e -> btn_LogoutActionPerformed(e));

            //---- jLabel1 ----
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/oop_motorph/img/img_myrecord.png")));

            //---- jLabel3 ----
            jLabel3.setIcon(new ImageIcon(getClass().getResource("/oop_motorph/img/img_emprecords.png")));

            //---- jLabel4 ----
            jLabel4.setIcon(new ImageIcon(getClass().getResource("/oop_motorph/img/img_logout.png")));

            //======== jPanel5 ========
            {

                GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                    jPanel5Layout.createParallelGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                );
                jPanel5Layout.setVerticalGroup(
                    jPanel5Layout.createParallelGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                );
            }

            //======== jPanel6 ========
            {

                GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                    jPanel6Layout.createParallelGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                );
                jPanel6Layout.setVerticalGroup(
                    jPanel6Layout.createParallelGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                );
            }

            GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup()
                .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup()
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(jPanel1Layout.createParallelGroup()
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel1))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_MyRecords, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel3))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(jPanel1Layout.createParallelGroup()
                                .addComponent(btn_EmpRecords, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel4))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(btn_Logout, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addGroup(jPanel1Layout.createParallelGroup()
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_Profile, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55)
                            .addComponent(btn_LeaveMgt, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(btn_SalaryAndStatutory, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(btn_PayrollSummary, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup()
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Profile)
                        .addComponent(btn_LeaveMgt)
                        .addComponent(btn_SalaryAndStatutory)
                        .addComponent(btn_PayrollSummary))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(btn_MyRecords, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(btn_EmpRecords, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(btn_Logout, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PayrollSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PayrollSummaryActionPerformed
        
        new frm_EmpPayroll().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_PayrollSummaryActionPerformed

    private void btn_SalaryAndStatutoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalaryAndStatutoryActionPerformed
        
        new frm_EmpSalary().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_SalaryAndStatutoryActionPerformed

    private void btn_LeaveMgtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LeaveMgtActionPerformed
        
        new frm_EmpAttLeave().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_LeaveMgtActionPerformed

    private void btn_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProfileActionPerformed
        new frm_EmpProfile().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_ProfileActionPerformed

    private void btn_MyRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MyRecordsActionPerformed
        
        new frm_EmpProfile().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_MyRecordsActionPerformed

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        CSVHandler.handleLogout(this); 
        
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void btn_EmpRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpRecordsActionPerformed
        
        new frm_EmployeesRecords().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_EmpRecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_EmpSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_EmpSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_EmpSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_EmpSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_EmpSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JTextField txt_sssNo;
    private JTextField txt_philhealthNo;
    private JTextField txt_pagibigNo;
    private JTextField txt_tinNo;
    private JTextField txt_basicSalary;
    private JTextField txt_riceAllow;
    private JTextField txt_phoneAllow;
    private JTextField txt_clothingAllow;
    private JTextField txt_grossSemi;
    private JTextField txt_hourlyRate;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JPanel jPanel3;
    private JButton btn_Profile;
    private JButton btn_LeaveMgt;
    private JButton btn_SalaryAndStatutory;
    private JButton btn_PayrollSummary;
    private JPanel jPanel4;
    private JButton btn_MyRecords;
    private JButton btn_EmpRecords;
    private JButton btn_Logout;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    private void applyModernStyling() {
        // Style the main panels with clean background
        jPanel1.setBackground(new Color(249, 250, 251));
        jPanel2.setBackground(new Color(255, 255, 255));
        jPanel3.setBackground(new Color(255, 255, 255));
        
        // Style navigation panel
        if (jPanel4 != null) {
            jPanel4.setBackground(new Color(255, 255, 255));
        }
        if (jPanel5 != null) {
            jPanel5.setBackground(new Color(255, 255, 255));
        }
        if (jPanel6 != null) {
            jPanel6.setBackground(new Color(255, 255, 255));
        }
        
        // Add enhanced card-like styling to main content panel - reduced padding for more space
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createEmptyBorder(4, 4, 8, 8),
                javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0, 8), 1)
            ),
            javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new Color(229, 231, 235), 1),
                javax.swing.BorderFactory.createEmptyBorder(16, 20, 16, 20)
            )
        ));
        
        // Style the navigation area with minimal border - reduced padding since title is removed
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(229, 231, 235)),
            javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8)
        ));
        
        // Style text fields with enhanced modern borders and improved spacing
        styleTextFieldEnhanced(txt_sssNo);
        styleTextFieldEnhanced(txt_philhealthNo);
        styleTextFieldEnhanced(txt_pagibigNo);
        styleTextFieldEnhanced(txt_tinNo);
        styleTextFieldEnhanced(txt_basicSalary);
        styleTextFieldEnhanced(txt_riceAllow);
        styleTextFieldEnhanced(txt_phoneAllow);
        styleTextFieldEnhanced(txt_clothingAllow);
        styleTextFieldEnhanced(txt_grossSemi);
        styleTextFieldEnhanced(txt_hourlyRate);
        
        // Style labels with enhanced modern typography
        styleLabelEnhanced(jLabel6, false);
        styleLabelEnhanced(jLabel7, false);
        styleLabelEnhanced(jLabel8, false);
        styleLabelEnhanced(jLabel9, false);
        styleLabelEnhanced(jLabel10, false);
        styleLabelEnhanced(jLabel11, false);
        styleLabelEnhanced(jLabel12, false);
        styleLabelEnhanced(jLabel13, false);
        styleLabelEnhanced(jLabel14, false);
        styleLabelEnhanced(jLabel15, false);
        
        // Style navigation buttons with enhanced modern design and better spacing
        styleNavigationButtonEnhanced(btn_Profile, new Color(107, 114, 128), false);
        styleNavigationButtonEnhanced(btn_LeaveMgt, new Color(107, 114, 128), false);
        styleNavigationButtonEnhanced(btn_SalaryAndStatutory, new Color(34, 197, 94), true); // Active green
        styleNavigationButtonEnhanced(btn_PayrollSummary, new Color(107, 114, 128), false);
        
        // Style left sidebar buttons with different sizing
        styleSidebarButtonEnhanced(btn_MyRecords, new Color(107, 114, 128), false);
        styleSidebarButtonEnhanced(btn_EmpRecords, new Color(107, 114, 128), false);
        styleSidebarButtonEnhanced(btn_Logout, new Color(239, 68, 68), false); // Red for logout
        
        // Add generous spacing improvements to the overall layout - comfortable padding for better UX
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
    }
    
    private void styleTextFieldEnhanced(javax.swing.JTextField field) {
        field.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        field.setBackground(new Color(249, 250, 251));
        field.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createEmptyBorder(1, 1, 2, 2),
                javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0, 6), 1)
            ),
            javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new Color(209, 213, 219), 1),
                javax.swing.BorderFactory.createEmptyBorder(10, 16, 10, 16)
            )
        ));
        field.setForeground(new Color(55, 65, 81));
    }
    
    private void styleLabelEnhanced(javax.swing.JLabel label, boolean isTitle) {
        if (isTitle) {
            label.setFont(new Font("Segoe UI", Font.BOLD, 22));
            label.setForeground(new Color(17, 24, 39));
        } else {
            label.setFont(new Font("Segoe UI", Font.BOLD, 14));
            label.setForeground(new Color(75, 85, 99));
            label.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 4, 0));
            // Add right alignment for consistent label positioning
            label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        }
    }
    
    private void styleNavigationButtonEnhanced(javax.swing.JButton button, Color backgroundColor, boolean isActive) {
        button.setFont(new Font("Segoe UI", Font.BOLD, 12));
        button.setBackground(backgroundColor);
        button.setForeground(new Color(255, 255, 255));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        
        // Set consistent preferred size for all navigation buttons
        button.setPreferredSize(new java.awt.Dimension(200, 45));
        button.setMinimumSize(new java.awt.Dimension(200, 45));
        button.setMaximumSize(new java.awt.Dimension(200, 45));
        
        // Ensure text is centered and properly aligned
        button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        
        if (isActive) {
            // Active button with enhanced border highlight and shadow
            button.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createEmptyBorder(1, 1, 3, 3),
                    javax.swing.BorderFactory.createLineBorder(new Color(34, 197, 94, 40), 1)
                ),
                javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(new Color(34, 197, 94), 2),
                    javax.swing.BorderFactory.createEmptyBorder(10, 16, 10, 16)
                )
            ));
        } else {
            // Regular button with subtle shadow and generous padding
            button.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createEmptyBorder(1, 1, 3, 3),
                javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0, 8), 1),
                    javax.swing.BorderFactory.createEmptyBorder(12, 18, 12, 18)
                )
            ));
        }
    }
    
    private void styleSidebarButtonEnhanced(javax.swing.JButton button, Color backgroundColor, boolean isActive) {
        button.setFont(new Font("Segoe UI", Font.BOLD, 13));
        button.setBackground(backgroundColor);
        button.setForeground(new Color(255, 255, 255));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        
        // Force exact uniform size for ALL sidebar buttons - 170px to match profile page
        button.setPreferredSize(new java.awt.Dimension(170, 45));
        button.setMinimumSize(new java.awt.Dimension(170, 45));
        button.setMaximumSize(new java.awt.Dimension(170, 45));
        button.setSize(170, 45);
        
        // Perfect alignment and spacing for sidebar buttons
        button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        
        // Clean, uniform styling for all sidebar buttons
        button.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createEmptyBorder(2, 2, 4, 4),
                javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0, 8), 1)
            ),
            javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new Color(156, 163, 175), 1),
                javax.swing.BorderFactory.createEmptyBorder(10, 12, 10, 12)
            )
        ));
    }
    
    private void addHoverEffects() {
        addButtonHoverEnhanced(btn_Profile, new Color(107, 114, 128), new Color(75, 85, 99));
        addButtonHoverEnhanced(btn_LeaveMgt, new Color(107, 114, 128), new Color(75, 85, 99));
        addButtonHoverEnhanced(btn_SalaryAndStatutory, new Color(34, 197, 94), new Color(22, 163, 74));
        addButtonHoverEnhanced(btn_PayrollSummary, new Color(107, 114, 128), new Color(75, 85, 99));
        
        // Add hover effects for sidebar buttons
        addButtonHoverEnhanced(btn_MyRecords, new Color(107, 114, 128), new Color(75, 85, 99));
        addButtonHoverEnhanced(btn_EmpRecords, new Color(107, 114, 128), new Color(75, 85, 99));
        addButtonHoverEnhanced(btn_Logout, new Color(239, 68, 68), new Color(220, 38, 38));
    }
    
    private void addButtonHoverEnhanced(javax.swing.JButton button, Color normalColor, Color hoverColor) {
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (button.isEnabled()) {
                    button.setBackground(hoverColor);
                    // Different hover effects for navigation vs sidebar buttons
                    if (button == btn_SalaryAndStatutory) {
                        // Active Salary button hover
                        button.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                            javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createEmptyBorder(0, 0, 4, 4),
                                javax.swing.BorderFactory.createLineBorder(new Color(34, 197, 94, 60), 1)
                            ),
                            javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new Color(34, 197, 94), 2),
                                javax.swing.BorderFactory.createEmptyBorder(10, 16, 10, 16)
                            )
                        ));
                    } else if (button == btn_Profile || button == btn_LeaveMgt || button == btn_PayrollSummary) {
                        // Navigation buttons hover
                        button.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                            javax.swing.BorderFactory.createEmptyBorder(0, 0, 4, 4),
                            javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0, 15), 1),
                                javax.swing.BorderFactory.createEmptyBorder(12, 18, 12, 18)
                            )
                        ));
                    } else {
                        // Sidebar buttons hover - uniform effect
                        button.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                            javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 5),
                                javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0, 12), 1)
                            ),
                            javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new Color(156, 163, 175), 1),
                                javax.swing.BorderFactory.createEmptyBorder(10, 12, 10, 12)
                            )
                        ));
                    }
                }
            }
            
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                if (button.isEnabled()) {
                    button.setBackground(normalColor);
                    // Reset to normal border
                    if (button == btn_SalaryAndStatutory) {
                        // Active Salary button normal
                        button.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                            javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createEmptyBorder(1, 1, 3, 3),
                                javax.swing.BorderFactory.createLineBorder(new Color(34, 197, 94, 40), 1)
                            ),
                            javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new Color(34, 197, 94), 2),
                                javax.swing.BorderFactory.createEmptyBorder(10, 16, 10, 16)
                            )
                        ));
                    } else if (button == btn_Profile || button == btn_LeaveMgt || button == btn_PayrollSummary) {
                        // Navigation buttons normal
                        button.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                            javax.swing.BorderFactory.createEmptyBorder(1, 1, 3, 3),
                            javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0, 8), 1),
                                javax.swing.BorderFactory.createEmptyBorder(12, 18, 12, 18)
                            )
                        ));
                    } else {
                        // Sidebar buttons normal - restore uniform styling
                        button.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                            javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createEmptyBorder(2, 2, 4, 4),
                                javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0, 8), 1)
                            ),
                            javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new Color(156, 163, 175), 1),
                                javax.swing.BorderFactory.createEmptyBorder(10, 12, 10, 12)
                            )
                        ));
                    }
                }
            }
        });
    }
}
