
package oop_motorph;

import java.awt.*;
import java.util.List;
import java.util.Map;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.border.*;


public class frm_EmpSalary extends javax.swing.JFrame {

   
    public frm_EmpSalary() {
        initComponents();
        
        //JBF: Sets the windown to center and disable resizable
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Payroll Information");

        
        EmpDetails employee = EmpUserSession.getInstance().getCurrentUser();
        if (employee != null) {
            // Load salary data from CSV
            List<EmpSalaryDetails> salaryData = CSVHandler.getSalaryData();
            EmpSalaryDetails salaryDetails = null;

            // Find the salary details for the logged-in employee
            for (EmpSalaryDetails details : salaryData) {
                if (details.getEmpID().equals(employee.getEmpID())) {
                    salaryDetails = details;
                    break;
                }
            }

            if (salaryDetails != null) {
                // Set the salary data in the form
                setSalaryData(salaryDetails);
            } else {
                JOptionPane.showMessageDialog(this, "Salary data not found for the user!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "User not logged in!", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Set role-based access
        String role = CSVHandler.loadCredentials().get(employee.getEmpID())[1];
        setRoleBasedAccess(role);
    }

    // Method to set salary data in the form
    private void setSalaryData(EmpSalaryDetails salaryDetails) {
        txt_sssNo.setText(salaryDetails.getSssNo());
        txt_philhealthNo.setText(salaryDetails.getPhilhealthNo());
        txt_tinNo.setText(salaryDetails.getTinNo());
        txt_pagibigNo.setText(salaryDetails.getPagibigNo());
        txt_basicSalary.setText(String.valueOf(salaryDetails.getBasicSalary()));
        txt_riceAllow.setText(String.valueOf(salaryDetails.getRiceSubsidy()));
        txt_phoneAllow.setText(String.valueOf(salaryDetails.getPhoneAllowance()));
        txt_clothingAllow.setText(String.valueOf(salaryDetails.getClothingAllowance()));
        txt_grossSemi.setText(String.valueOf(salaryDetails.getGrossSemi()));
        txt_hourlyRate.setText(String.valueOf(salaryDetails.getHourlyRate()));
    }

    // Method to set role-based access
    // Method to set role-based access
    public void setRoleBasedAccess(String role) {
        // Disable all buttons by default
        btn_EmpRecords.setEnabled(false);
        btn_PayrollSummary.setEnabled(false);
        btn_Profile.setEnabled(false);
        btn_MyRecords.setEnabled(false);
        // btn_SalaryAndStatutory.setEnabled(false); // Optional: Uncomment if used elsewhere

        switch (role.toUpperCase()) {
            case "HR":
                // HR can access everything
                btn_EmpRecords.setEnabled(true);
                btn_PayrollSummary.setEnabled(true);
                btn_Profile.setEnabled(true);
                btn_MyRecords.setEnabled(true);
                // btn_SalaryAndStatutory.setEnabled(true); // Optional
                break;

            case "EMPLOYEE":
                // Employee access is limited
                btn_Profile.setEnabled(true);
                btn_MyRecords.setEnabled(true);
                btn_PayrollSummary.setEnabled(true);
                break;

            default:
                JOptionPane.showMessageDialog(this, "Invalid role: " + role, "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        txt_sssNo = new JTextField();
        txt_philhealthNo = new JTextField();
        txt_pagibigNo = new JTextField();
        txt_tinNo = new JTextField();
        txt_basicSalary = new JTextField();
        txt_riceAllow = new JTextField();
        txt_phoneAllow = new JTextField();
        txt_clothingAllow = new JTextField();
        txt_grossSemi = new JTextField();
        txt_hourlyRate = new JTextField();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        jLabel11 = new JLabel();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        jLabel14 = new JLabel();
        jLabel15 = new JLabel();
        jLabel2 = new JLabel();
        jPanel3 = new JPanel();
        btn_Profile = new JButton();
        btn_LeaveMgt = new JButton();
        btn_SalaryAndStatutory = new JButton();
        btn_PayrollSummary = new JButton();
        jPanel4 = new JPanel();
        btn_MyRecords = new JButton();
        btn_EmpRecords = new JButton();
        btn_Logout = new JButton();
        jLabel1 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jPanel5 = new JPanel();
        jPanel6 = new JPanel();
        jLabel5 = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        var contentPane = getContentPane();

        //======== jPanel1 ========
        {
            jPanel1.setBorder(new CompoundBorder());
            jPanel1.setBorder ( new javax . swing. border .CompoundBorder ( new javax . swing. border .TitledBorder ( new javax . swing. border .EmptyBorder
            ( 0, 0 ,0 , 0) ,  "JF\u006frmDes\u0069gner \u0045valua\u0074ion" , javax. swing .border . TitledBorder. CENTER ,javax . swing. border
            .TitledBorder . BOTTOM, new java. awt .Font ( "D\u0069alog", java .awt . Font. BOLD ,12 ) ,java . awt
            . Color .red ) ,jPanel1. getBorder () ) ); jPanel1. addPropertyChangeListener( new java. beans .PropertyChangeListener ( ){ @Override public void
            propertyChange (java . beans. PropertyChangeEvent e) { if( "\u0062order" .equals ( e. getPropertyName () ) )throw new RuntimeException( )
            ;} } );

            //======== jPanel2 ========
            {
                jPanel2.setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED, null, Color.lightGray, null, null));

                //---- txt_sssNo ----
                txt_sssNo.setEditable(false);

                //---- txt_philhealthNo ----
                txt_philhealthNo.setEditable(false);

                //---- txt_pagibigNo ----
                txt_pagibigNo.setEditable(false);

                //---- txt_tinNo ----
                txt_tinNo.setEditable(false);

                //---- txt_basicSalary ----
                txt_basicSalary.setEditable(false);

                //---- txt_riceAllow ----
                txt_riceAllow.setEditable(false);

                //---- txt_phoneAllow ----
                txt_phoneAllow.setEditable(false);

                //---- txt_clothingAllow ----
                txt_clothingAllow.setEditable(false);

                //---- txt_grossSemi ----
                txt_grossSemi.setEditable(false);

                //---- txt_hourlyRate ----
                txt_hourlyRate.setEditable(false);

                //---- jLabel6 ----
                jLabel6.setText("SSS Number:");

                //---- jLabel7 ----
                jLabel7.setText("Philhealth Number:");

                //---- jLabel8 ----
                jLabel8.setText("Pagibig Number:");

                //---- jLabel9 ----
                jLabel9.setText("TIN Number:");

                //---- jLabel10 ----
                jLabel10.setText("Basic Salary:");

                //---- jLabel11 ----
                jLabel11.setText("Rice Subsidy Allowance:");

                //---- jLabel12 ----
                jLabel12.setText("Phone Allowance:");

                //---- jLabel13 ----
                jLabel13.setText("Clothing Allowance:");

                //---- jLabel14 ----
                jLabel14.setText("Gross Semi-Monthly Rate:");

                //---- jLabel15 ----
                jLabel15.setText("Hourly Rate:");

                GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup()
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap(94, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup()
                                .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel11, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel13, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE))
                            .addGap(52, 52, 52)
                            .addGroup(jPanel2Layout.createParallelGroup()
                                .addComponent(txt_hourlyRate, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_grossSemi, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_clothingAllow, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_phoneAllow, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_riceAllow, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_basicSalary, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_tinNo, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_pagibigNo, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_philhealthNo, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_sssNo, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE))
                            .addGap(74, 74, 74))
                );
                jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup()
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap(90, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(txt_sssNo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_philhealthNo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_pagibigNo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_tinNo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_basicSalary, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_riceAllow, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_phoneAllow, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel12))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_clothingAllow, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_grossSemi, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_hourlyRate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addGap(23, 23, 23))
                );
            }

            //---- jLabel2 ----
            jLabel2.setText("MotorPH");

            //======== jPanel3 ========
            {

                GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                    jPanel3Layout.createParallelGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel3Layout.setVerticalGroup(
                    jPanel3Layout.createParallelGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                );
            }

            //---- btn_Profile ----
            btn_Profile.setText("Profile");
            btn_Profile.addActionListener(e -> btn_ProfileActionPerformed(e));

            //---- btn_LeaveMgt ----
            btn_LeaveMgt.setText("Attendance & Leave");
            btn_LeaveMgt.addActionListener(e -> btn_LeaveMgtActionPerformed(e));

            //---- btn_SalaryAndStatutory ----
            btn_SalaryAndStatutory.setText("Salary & Statutory");
            btn_SalaryAndStatutory.addActionListener(e -> btn_SalaryAndStatutoryActionPerformed(e));

            //---- btn_PayrollSummary ----
            btn_PayrollSummary.setText("Payroll Summary");
            btn_PayrollSummary.addActionListener(e -> btn_PayrollSummaryActionPerformed(e));

            //======== jPanel4 ========
            {

                GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                    jPanel4Layout.createParallelGroup()
                        .addGap(0, 1032, Short.MAX_VALUE)
                );
                jPanel4Layout.setVerticalGroup(
                    jPanel4Layout.createParallelGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                );
            }

            //---- btn_MyRecords ----
            btn_MyRecords.setText("My Records");
            btn_MyRecords.addActionListener(e -> btn_MyRecordsActionPerformed(e));

            //---- btn_EmpRecords ----
            btn_EmpRecords.setText("Employee Records");
            btn_EmpRecords.addActionListener(e -> btn_EmpRecordsActionPerformed(e));

            //---- btn_Logout ----
            btn_Logout.setText("Logout");
            btn_Logout.addActionListener(e -> btn_LogoutActionPerformed(e));

            //---- jLabel1 ----
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/oop_motorph/img/img_myrecord.png")));

            //---- jLabel3 ----
            jLabel3.setIcon(new ImageIcon(getClass().getResource("/oop_motorph/img/img_emprecords.png")));

            //---- jLabel4 ----
            jLabel4.setIcon(new ImageIcon(getClass().getResource("/oop_motorph/img/img_logout.png")));

            //======== jPanel5 ========
            {

                GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                    jPanel5Layout.createParallelGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                );
                jPanel5Layout.setVerticalGroup(
                    jPanel5Layout.createParallelGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                );
            }

            //======== jPanel6 ========
            {

                GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                    jPanel6Layout.createParallelGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                );
                jPanel6Layout.setVerticalGroup(
                    jPanel6Layout.createParallelGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                );
            }

            //---- jLabel5 ----
            jLabel5.setText("Version 1.30");

            GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup()
                    .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup()
                                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(56, 56, 56))
                                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup()
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel5))
                                        .addGap(67, 67, 67))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup()
                                    .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup()
                                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup()
                                            .addComponent(btn_EmpRecords)
                                            .addComponent(btn_MyRecords, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_Logout, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31))
                                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(55, 55, 55)))))
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_Profile, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btn_LeaveMgt, GroupLayout.PREFERRED_SIZE, 184, GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btn_SalaryAndStatutory, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btn_PayrollSummary, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Profile)
                            .addComponent(btn_LeaveMgt)
                            .addComponent(btn_SalaryAndStatutory)
                            .addComponent(btn_PayrollSummary)
                            .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_MyRecords)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_EmpRecords)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Logout))
                            .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            );
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PayrollSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PayrollSummaryActionPerformed
        
        new frm_EmpPayroll().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_PayrollSummaryActionPerformed

    private void btn_SalaryAndStatutoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalaryAndStatutoryActionPerformed
        
        new frm_EmpSalary().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_SalaryAndStatutoryActionPerformed

    private void btn_LeaveMgtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LeaveMgtActionPerformed
        
        new frm_EmpAttLeave().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_LeaveMgtActionPerformed

    private void btn_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProfileActionPerformed
        new frm_EmpProfile().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_ProfileActionPerformed

    private void btn_MyRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MyRecordsActionPerformed
        
        new frm_EmpProfile().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_MyRecordsActionPerformed

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        CSVHandler.handleLogout(this); 
        
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void btn_EmpRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpRecordsActionPerformed
        
        new frm_EmployeesRecords().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_EmpRecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_EmpSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_EmpSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_EmpSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_EmpSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_EmpSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JTextField txt_sssNo;
    private JTextField txt_philhealthNo;
    private JTextField txt_pagibigNo;
    private JTextField txt_tinNo;
    private JTextField txt_basicSalary;
    private JTextField txt_riceAllow;
    private JTextField txt_phoneAllow;
    private JTextField txt_clothingAllow;
    private JTextField txt_grossSemi;
    private JTextField txt_hourlyRate;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel2;
    private JPanel jPanel3;
    private JButton btn_Profile;
    private JButton btn_LeaveMgt;
    private JButton btn_SalaryAndStatutory;
    private JButton btn_PayrollSummary;
    private JPanel jPanel4;
    private JButton btn_MyRecords;
    private JButton btn_EmpRecords;
    private JButton btn_Logout;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
